packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  "@nestjs/core": true
  "@prisma/client": true
  "@prisma/engines": true
  "prisma": true
  "unrs-resolver": true
  "bcrypt": true
  msgpackr-extract: true

minimumReleaseAgeExclude:
  - "pnpm@11.13.0"
